package com.myspace.discount;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Profile implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.lang.String name;
	private int discount;

	public Profile() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	public Profile(java.lang.String type, java.lang.String name, int discount) {
		this.type = type;
		this.name = name;
		this.discount = discount;
	}

}